<h2>Phim</h2>
<p>
    <?php
    $name = $block->getInfo()->getData();

    $movie = $block->getMovie();
//    foreach ($movie as $value) {
//        echo "+) Movie: ".$value['name'] . "</br>";
//        foreach ($name as $item) {
//            if ($value['name'] == $item['name'])
//                echo "- Director: " . $item['director_name']."<br>";
//        }
//    }

    foreach ($name as $item) {
        echo "+) Movie: ".$item['name']."<br>";
        echo "- Director: " . $item['director_name'] . "<br>";
    }

    $actor = $block->getActor();
    echo "Actor: <br>";
    foreach ($actor as $value){
        echo $value['name']."  ";
    }
    ?>

</p>