<h2>Phim</h2>
<p>
    <?php
    $name = $block->getInfo();

    echo '+) Movie: '.'<br>';
    foreach ($name as $item) {
        echo ' - '.$item->getName().' - ';
        echo 'Director: '. $item->getDirectorname() . '<br>';
    }
//    $movie = $block->getMovie();
//    foreach ($movie as $value){
//        echo $value->getName().''<br>;
//    }

    $actor = $block->getActor();
    echo "+) Actor: <br>";
    foreach ($actor as $value){
        echo " - ".$value->getName();
    }
    ?>

</p>