<style>
    select {
        margin-bottom: 18px;
        width: 60%;
    }
</style>
<?php
$product = $block->getCurrentProduct();
$roomType = $product->getRoomtype(); ?>
<?php if (isset($roomType)): ?>
    <h3>Please Select The Hotel </h3>
    <?php $hotel = $block->getInfo() ?>
    <select name="hotel" id="hotel">
        <option value="">Select The Hotel</option>
        <?php foreach ($hotel as $option): ?>
            <?php if (!empty($option['available_' . $roomType])): ?>
                <option value="<?php echo $option['hotel_id'] ?> "> <?php echo $option['hotel_name'] ?> </option>
            <?php endif; ?>
        <?php endforeach; ?>
    </select>

<?php endif; ?>

<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/alert'], function ($, alert) {
        $("#hotel").change(function () {
            var value = $("#hotel").val();
            $.ajax({
                type: "POST",
                dataType: "json",
                url: "<?php echo
                $this->getUrl('hotel/index/hotelinfo') ?>",
                data: {hotel: value},
                success: function (result) {
                    alert({
                        title: "Hotel Information",
                        content: "Hotel Id: " + result.id +
                            "<br> Hotel Name: " + result.name +
                            "<br>City: " + result.city +
                            "<br>Phone: " + result.phone +
                            "<br>Available Single: " + result.single +
                            "<br>Available Double: " + result.double +
                            "<br>Available Triple: " + result.triple,
                        autoOpen: true,
                        clickableOverlay: true,
                    });
                },
                // error: function (error) {
                //     alert({
                //         title: "Warning",
                //         content: "This ID is not exist!",
                //         autoOpen: true,
                //         clickableOverlay: true,
                //     });
                // }
            });
        })
    })
</script>

